# Colors (Noctalia)

[colors.bright]
black = '{{colors.terminal_bright_black.default.hex}}'
blue = '{{colors.terminal_bright_blue.default.hex}}'
cyan = '{{colors.terminal_bright_cyan.default.hex}}'
green = '{{colors.terminal_bright_green.default.hex}}'
magenta = '{{colors.terminal_bright_magenta.default.hex}}'
red = '{{colors.terminal_bright_red.default.hex}}'
white = '{{colors.terminal_bright_white.default.hex}}'
yellow = '{{colors.terminal_bright_yellow.default.hex}}'

[colors.cursor]
cursor = '{{colors.terminal_cursor.default.hex}}'
text = '{{colors.terminal_cursor_text.default.hex}}'

[colors.normal]
black = '{{colors.terminal_normal_black.default.hex}}'
blue = '{{colors.terminal_normal_blue.default.hex}}'
cyan = '{{colors.terminal_normal_cyan.default.hex}}'
green = '{{colors.terminal_normal_green.default.hex}}'
magenta = '{{colors.terminal_normal_magenta.default.hex}}'
red = '{{colors.terminal_normal_red.default.hex}}'
white = '{{colors.terminal_normal_white.default.hex}}'
yellow = '{{colors.terminal_normal_yellow.default.hex}}'

[colors.primary]
background = '{{colors.terminal_background.default.hex}}'
foreground = '{{colors.terminal_foreground.default.hex}}'

[colors.selection]
background = '{{colors.terminal_selection_bg.default.hex}}'
text = '{{colors.terminal_selection_fg.default.hex}}'
