pragma Singleton

import QtQuick
import Quickshell
import qs.Commons
import qs.Services.Theming
import qs.Services.UI

// Predefined color schemes were removed: colors are always generated by the
// template processor — from the wallpaper, or from the accent seed color when
// `colorSchemes.accentColor` is set (see AppThemeService / TemplateProcessor).
// This service only keeps the system-appearance sync and the dark-mode toast.
Singleton {
  id: root

  readonly property string gtkRefreshScript: Quickshell.shellDir + "/Scripts/python/src/theming/gtk-refresh.py"

  // prefer-light/prefer-dark only; GTK template post_hook still runs full gtk-refresh.
  function pushSystemColorScheme() {
    if (!Settings.data.colorSchemes.syncGsettings)
      return;
    if (TemplateProcessor.isTemplateEnabled("gtk"))
      return;
    const mode = Settings.data.colorSchemes.darkMode ? "dark" : "light";
    Quickshell.execDetached(["python3", gtkRefreshScript, "--appearance-only", mode]);
  }

  Connections {
    target: Settings.data.colorSchemes
    function onDarkModeChanged() {
      Logger.d("ColorScheme", "Detected dark mode change");
      root.pushSystemColorScheme();
      // Toast: dark/light mode switched
      const enabled = !!Settings.data.colorSchemes.darkMode;
      const label = enabled ? I18n.tr("tooltips.switch-to-dark-mode") : I18n.tr("tooltips.switch-to-light-mode");
      const description = I18n.tr("common.enabled");
      ToastService.showNotice(label, description, "dark-mode");
    }
  }

  // --------------------------------
  function init() {
    // does nothing but ensure the singleton is created
    // do not remove
    Logger.i("ColorScheme", "Service started");
  }
}
