# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = dunst
exec-once = hyprsunset
exec-once = wpaperd -d
exec-once = wl-paste --type text --watch cliphist store
exec-once = qs