# ----------------------------------------------------- 
# Environment Variables
# ----------------------------------------------------- 

env = XCURSOR_THEME,BreezeX-Light
env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = MOZ_ENABLE_WAYLAND,1
env = CLUTTER_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC,1

#QT APPS
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

#NVIDIA
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = NVD_BACKEND,direct
# env = __GL_VRR_ALLOWED,1
# env = GBM_BACKEND,nvidia-drm
# env = __VK_LAYER_NV_optimus,NVIDIA_only