[colors]
background = #16161e
background-alt = #20212C
foreground = #acb0d0
foreground-alt = #5D5E72
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

red = #ff7a93

trans = #00000000
semi-trans-black = #cc000000

shade-1 = #32344a
shade-2 = #444b6a
shade-3 = #787c99
shade-4 = #CACACE
shade-5 = #acb0d0

[bar/mybar]
width = 100%
height = 20pt
radius = 0 

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace;2

modules-left = xworkspaces xwindow
modules-right = wlan eth battery pulseaudio date session

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right 

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%


[module/battery]
type = internal/battery
full-at = 98
low-at = 20
battery = BAT1
adapter = ACAD
poll-interval = 5
format-full-prefix =  
format-full = <label-charging>
format-charging-prefix =  
format-charging = <label-charging>
label-charging = %percentage:2%%
label-charging-padding = 1
format-charging-foreground = ${colors.fg}
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
label-discharging-padding = 1
format-discharging-foreground = ${colors.fg}
format-low = <ramp-capacity><label-discharging>
label-low-padding = 1
format-low-foreground = ${colors.red}
ramp-capacity-0 = ""
ramp-capacity-1 = ""
ramp-capacity-2 = ""
ramp-capacity-3 = ""
ramp-capacity-4 = ""
ramp-capacity-5 = ""

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false

format-volume = <label-volume>
format-volume-prefix = %{T4}%{T-}
format-volume-prefix-foreground = ${colors.foreground}
label-volume = %{T1}%percentage%%%{T-}
label-volume-foreground = ${colors.foreground}
label-volume-padding = 1

format-muted = <label-muted>
format-muted-prefix = 
format-muted-prefix-foreground = ${colors.foreground-alt}
label-muted = %{T1}%percentage%%%{T-}
label-muted-foreground = ${colors.foreground-alt}
label-muted-padding = 1

click-right = pavucontrol&


[module/wlan]
interface-type = wireless
type = internal/network
interface = wlan0
interval = 1.0

format-connected-prefix = 
format-connected = <label-connected>
label-connected = "%{A1:wifimenu:}%essid%%{A}"
label-connected-foreground = ${colors.foreground}
label-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-padding = 1
label-disconnected = %{A1:wifimenu:}%{A}
label-disconnected-foreground = ${colors.shade-1}
label-disconnected-padding = 1

[module/eth]
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %I:%M %P
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[module/session]
type = custom/text

click-left = powermenu
content = %{T4}%{T-}
content-background = ${colors.shade-2}
content-foreground = ${colors.shade-5}
content-padding = 1

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
